nome = str(input('Digite o seu nome completo: ')).strip()
nome2 = nome.split()
print ('Muito prazer em te conhecer!')
print (f'Seu primeiro nome é {nome2[0]}')
print (f'Seu último nome é {nome2[len(nome2)-1]}')